apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-service
spec:
  selector:
    app: guestbook-ui # Unified label
  ports:
    - port: 80
      targetPort: 80 # Targets guestbook-ui container

---
apiVersion: v1
kind: Service
metadata:
  name: soundbook-service
spec:
  type: NodePort
  selector:
    app: guestbook-ui # Unified label
  ports:
    - port: 8080
      targetPort: 80 # Targets soundbook container
      nodePort: 30002 # NodePort for external access
