apiVersion: v1
kind: Service
metadata:
  name: soundbook
spec:
  type: NodePort
  selector:
    app: soundbook
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002 # Ensure this is within the range 30000-32767
