apiVersion: apps/v1
kind: Deployment
metadata:
  name: soundbook
  labels:
    app: soundbook
spec:
  replicas: 1 # Set the number of replicas for scaling
  selector:
    matchLabels:
      app: soundbook
  template:
    metadata:
      labels:
        app: soundbook
    spec:
      containers:
        - name: soundbook
          image: akin11235/soundbook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "1Gi" # Increased memory request
              cpu: "500m"
            limits:
              memory: "2Gi" # Increased memory limit
              cpu: "1000m"
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048" # Increase Node.js memory limit to 2GB
