apiVersion: v1
kind: Service
metadata:
  name: soundbook
spec:
  type: NodePort
  selector:
    app: spotify-app
  ports:
    - port: 80
      targetPort: 4200
      # nodePort: 30001 # Ensure this is within the range 30000-32767
